"""
page_generator.py
-----------------
pSEO infrastructure generator for Geo-Subs Tracker.

Generates:
  - pages/<service>_<country>.py  for every Service × Country combination
  - sitemap.xml                   in the project root

Usage:
  python page_generator.py          # full run
  python page_generator.py --dry-run  # preview only, no files written
"""

import os
import sys
import argparse
from datetime import datetime, timezone
from itertools import product

# ── Configuration ─────────────────────────────────────────────────────────────

SERVICES = [
    "Netflix",
    "YouTube Premium",
    "Spotify",
    "Disney+",
    "Tidal",
    "Canva Pro",
]

COUNTRIES = [
    "Turkey",
    "Argentina",
    "Nigeria",
    "Egypt",
    "Pakistan",
    "Philippines",
    "India",
]

# Intents (used for sitemap metadata / future meta-tag injection)
INTENTS = [
    "price",
    "cheapest-subscription",
    "how-to-get-cheaper",
]

BASE_URL    = "https://geo-subs-tracker.streamlit.app"
PAGES_DIR   = os.path.join(os.path.dirname(__file__), "pages")
SITEMAP_OUT = os.path.join(os.path.dirname(__file__), "sitemap.xml")


# ── Slug helpers ──────────────────────────────────────────────────────────────

def to_slug(text: str) -> str:
    """Filesystem slug (underscores): 'YouTube Premium' → 'youtube_premium'."""
    return (
        text.lower()
            .replace("+", "_plus")
            .replace(" ", "_")
            .replace("-", "_")
    )


def to_url_slug(text: str) -> str:
    """
    Streamlit Cloud URL slug (hyphens).
    Streamlit converts 'netflix_turkey.py' → URL '/netflix-turkey'.
    'YouTube Premium' → 'youtube-premium', 'Disney+' → 'disney-plus'
    """
    return (
        text.lower()
            .replace("+", "-plus")
            .replace(" ", "-")
            .replace("_", "-")
    )


# ── Page file template ────────────────────────────────────────────────────────

PAGE_TEMPLATE = '''\
# Auto-generated by page_generator.py — DO NOT EDIT MANUALLY
# Service: {service}
# Country: {country}

import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from components.template import render_page

render_page(service="{service}", country="{country}")
'''


# ── Sitemap template ──────────────────────────────────────────────────────────

def build_sitemap(combos: list[tuple[str, str]]) -> str:
    """Return a complete sitemap.xml string for all pages."""
    today      = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    url_blocks = []

    # Homepage
    url_blocks.append(f"""  <url>
    <loc>{BASE_URL}/</loc>
    <lastmod>{today}</lastmod>
    <changefreq>daily</changefreq>
    <priority>1.0</priority>
  </url>""")

    # Sub-pages
    for service, country in combos:
        slug = f"{to_url_slug(service)}-{to_url_slug(country)}"
        url_blocks.append(f"""  <url>
    <loc>{BASE_URL}/{slug}</loc>
    <lastmod>{today}</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>""")

    body = "\n".join(url_blocks)
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
{body}
</urlset>
"""


# ── Core generation logic ─────────────────────────────────────────────────────

def generate(dry_run: bool = False) -> None:
    combos = list(product(SERVICES, COUNTRIES))
    total  = len(combos)

    print(f"  Services : {len(SERVICES)}")
    print(f"  Countries: {len(COUNTRIES)}")
    print(f"  Pages    : {total}")
    print(f"  Sitemap  : {SITEMAP_OUT}")
    print()

    if dry_run:
        print("[DRY RUN] No files written. Remove --dry-run to execute.")
        print()
        print("Files that would be created:")
        for service, country in combos:
            fname = f"{to_slug(service)}_{to_slug(country)}.py"
            print(f"  pages/{fname}")
        print(f"  sitemap.xml")
        return

    # Create directories
    os.makedirs(PAGES_DIR, exist_ok=True)

    # Ensure components/__init__.py exists (makes it importable as a package)
    components_dir = os.path.join(os.path.dirname(__file__), "components")
    os.makedirs(components_dir, exist_ok=True)
    init_path = os.path.join(components_dir, "__init__.py")
    if not os.path.exists(init_path):
        open(init_path, "w").close()

    # Write page files
    written = 0
    for service, country in combos:
        fname    = f"{to_slug(service)}_{to_slug(country)}.py"
        fpath    = os.path.join(PAGES_DIR, fname)
        content  = PAGE_TEMPLATE.format(service=service, country=country)

        with open(fpath, "w", encoding="utf-8") as f:
            f.write(content)
        written += 1
        print(f"  [+] pages/{fname}")

    # Write sitemap
    sitemap_content = build_sitemap(combos)
    with open(SITEMAP_OUT, "w", encoding="utf-8") as f:
        f.write(sitemap_content)
    print(f"\n  [+] sitemap.xml  ({total + 1} URLs)")

    print(f"\n  Done. {written} page files + sitemap written.")


# ── Entry point ───────────────────────────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="pSEO page generator for Geo-Subs Tracker")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Preview files to be generated without writing anything",
    )
    args = parser.parse_args()

    print("=== Geo-Subs Tracker — pSEO Page Generator ===\n")
    generate(dry_run=args.dry_run)
    sys.exit(0)
