# Auto-generated by page_generator.py — DO NOT EDIT MANUALLY
# Service: Spotify
# Country: India

import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from components.template import render_page

render_page(service="Spotify", country="India")
